// Rasterises Natural Earth 110m land polygons into a 360x180 (1°) bit grid for the launch globe.
//   node scripts/gen_land.mjs [path/to/ne_110m_land.geojson]
// Downloads the file when no path is given. Writes mobile/src/data/land.ts (bit-packed, base64).
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const URL = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson';
const W = 360, H = 180;

const src = process.argv[2] ? readFileSync(process.argv[2], 'utf8') : await (await fetch(URL)).text();
const geo = JSON.parse(src);
const polys = []; // [outer, ...holes], each ring = [[lng,lat],...]
for (const f of geo.features) {
  const g = f.geometry;
  if (g.type === 'Polygon') polys.push(g.coordinates);
  else if (g.type === 'MultiPolygon') for (const p of g.coordinates) polys.push(p);
}
const inRing = (ring, x, y) => {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i], [xj, yj] = ring[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};
const bits = new Uint8Array(Math.ceil((W * H) / 8));
let land = 0;
for (let r = 0; r < H; r++) {
  const lat = 90 - (r + 0.5); // row 0 = north pole
  for (let c = 0; c < W; c++) {
    const lng = -180 + (c + 0.5);
    let on = false;
    for (const rings of polys) {
      if (!inRing(rings[0], lng, lat)) continue;
      on = true;
      for (let h = 1; h < rings.length; h++) if (inRing(rings[h], lng, lat)) { on = false; break; }
      if (on) break;
    }
    if (on) { const i = r * W + c; bits[i >> 3] |= 1 << (i & 7); land++; }
  }
}
const b64 = Buffer.from(bits).toString('base64');
const out = `// Generated by scripts/gen_land.mjs from Natural Earth 110m land (public domain). Do not edit.
// 360x180 cells, 1° each, row 0 = north pole, column 0 = 180°W; bit set = land. ${land} land cells.
export const LAND_W = ${W};
export const LAND_H = ${H};
export const LAND_B64 = '${b64}';
`;
writeFileSync(resolve('mobile/src/data/land.ts'), out);
console.log(`land cells: ${land} / ${W * H} (${((100 * land) / (W * H)).toFixed(1)}%), ${b64.length} chars`);
